project_name   = "gatus"
domain_name    = "gatus.moabdullahi.uk"
hosted_zone_id = "Z082746722X4CRQTYQN48"
aws_region     = "eu-west-2"
container_image = "REDACTED.dkr.ecr.eu-west-2.amazonaws.com/gatus:latest"