endpoints:
  - name: gatus-health
    group: project
    url: "https://gatus.moabdullahi.uk/health"
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == UP"

  - name: gatus-ui
    group: project
    url: "https://gatus.moabdullahi.uk/"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 2000"

  - name: github
    group: external
    url: "https://github.com"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"

  - name: aws
    group: external
    url: "https://aws.amazon.com"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"

  - name: google
    group: external
    url: "https://www.google.com"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"

  - name: cloudflare-dns
    group: network
    url: "1.1.1.1"
    interval: 5m
    dns:
      query-name: "gatus.moabdullahi.uk"
      query-type: "A"
    conditions:
      - "[DNS_RCODE] == NOERROR"

  - name: google-dns
    group: network
    url: "8.8.8.8"
    interval: 5m
    dns:
      query-name: "gatus.moabdullahi.uk"
      query-type: "A"
    conditions:
      - "[DNS_RCODE] == NOERROR"