name: Build and Push Image

on: 
  push:
    branches:
      - main
    paths:
      - "app/**"
      - "Dockerfile"
      - ".github/workflows/docker-build-push.yml"
  workflow_dispatch:

permissions:
  id-token: write 
  contents: read

jobs: 
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-west-2
      ECR_REPOSITORY: gatus

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV 

      - name: Build Docker image
        run: | 
          docker build -f ./Dockerfile -t $ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REPOSITORY:latest .

      - name: Scan image for vulnerabilities
        uses: aquasecurity/trivy-action@0.35.0
        with:
          image-ref: ${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          format: table
          exit-code: "1"
          ignore-unfixed: true
          severity: CRITICAL,HIGH
          
      - name: Tag image for ECR
        run: | 
          docker tag $ECR_REPOSITORY:$IMAGE_TAG ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG
          docker tag $ECR_REPOSITORY:latest ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest

      - name: Push image to ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest